"""add full schema

Revision ID: c730b822296a
Revises: 472409161500
Create Date: 2026-06-05 09:18:15.959679
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = 'c730b822296a'
down_revision: str | None = '472409161500'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_language', sa.String(length=32), server_default='python', nullable=False),
    sa.Column('source_pdf_url', sa.Text(), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'generating', 'ready', 'published', 'failed', name='coursestatus', native_enum=False), server_default='draft', nullable=False),
    sa.Column('generation_phase', sa.Enum('extracting', 'chunking', 'embedding', 'outline', 'blocks', 'tts', name='generationphase', native_enum=False), nullable=True),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('total_lessons', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_blocks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_courses_creator_id'), 'courses', ['creator_id'], unique=False)
    op.create_table('course_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_chunks_course_id'), 'course_chunks', ['course_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('objectives', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('generating', 'ready', 'failed', name='lessonstatus', native_enum=False), server_default='generating', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'position')
    )
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('markdown', 'code', 'mermaid', 'concept_check', 'understanding_check', name='blocktype', native_enum=False), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tts_audio_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'position')
    )
    op.create_index(op.f('ix_blocks_lesson_id'), 'blocks', ['lesson_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('current_lesson_id', sa.Uuid(), nullable=True),
    sa.Column('current_block_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_block_id'], ['blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id')
    )
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('block_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='blockprogressstatus', native_enum=False), server_default='not_started', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'block_id')
    )
    op.create_index(op.f('ix_block_progress_block_id'), 'block_progress', ['block_id'], unique=False)
    op.create_index(op.f('ix_block_progress_enrollment_id'), 'block_progress', ['enrollment_id'], unique=False)
    op.create_table('code_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('judge0_token', sa.String(length=64), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.Enum('passed', 'failed', 'runtime_error', 'compile_error', 'error', name='codeverdict', native_enum=False), nullable=True),
    sa.Column('socratic_hint', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_submissions_block_id'), 'code_submissions', ['block_id'], unique=False)
    op.create_index(op.f('ix_code_submissions_enrollment_id'), 'code_submissions', ['enrollment_id'], unique=False)
    op.create_table('concept_check_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=False),
    sa.Column('selected_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_check_attempts_block_id'), 'concept_check_attempts', ['block_id'], unique=False)
    op.create_index(op.f('ix_concept_check_attempts_enrollment_id'), 'concept_check_attempts', ['enrollment_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('source_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_enrollment_id'), 'questions', ['enrollment_id'], unique=False)
    op.create_table('understanding_check_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('poor', 'fair', 'good', 'excellent', name='understandinglevel', native_enum=False), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('missing_points', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_understanding_check_attempts_block_id'), 'understanding_check_attempts', ['block_id'], unique=False)
    op.create_index(op.f('ix_understanding_check_attempts_enrollment_id'), 'understanding_check_attempts', ['enrollment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_understanding_check_attempts_enrollment_id'), table_name='understanding_check_attempts')
    op.drop_index(op.f('ix_understanding_check_attempts_block_id'), table_name='understanding_check_attempts')
    op.drop_table('understanding_check_attempts')
    op.drop_index(op.f('ix_questions_enrollment_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_concept_check_attempts_enrollment_id'), table_name='concept_check_attempts')
    op.drop_index(op.f('ix_concept_check_attempts_block_id'), table_name='concept_check_attempts')
    op.drop_table('concept_check_attempts')
    op.drop_index(op.f('ix_code_submissions_enrollment_id'), table_name='code_submissions')
    op.drop_index(op.f('ix_code_submissions_block_id'), table_name='code_submissions')
    op.drop_table('code_submissions')
    op.drop_index(op.f('ix_block_progress_enrollment_id'), table_name='block_progress')
    op.drop_index(op.f('ix_block_progress_block_id'), table_name='block_progress')
    op.drop_table('block_progress')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_blocks_lesson_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_course_chunks_course_id'), table_name='course_chunks')
    op.drop_table('course_chunks')
    op.drop_index(op.f('ix_courses_creator_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
